Update main_edu-cart-service.yml

diff --git a/.github/workflows/main_edu-cart-service.yml b/.github/workflows/main_edu-cart-service.yml
--- a/.github/workflows/main_edu-cart-service.yml
+++ b/.github/workflows/main_edu-cart-service.yml
@@ -21,19 +21,33 @@ jobs:
       - name: Set up .NET Core
         uses: actions/setup-dotnet@v4
         with:
-          dotnet-version: '8.x'
+          dotnet-version: '8.x.x'
 
+      - name: Add appsettings.json
+        run: |
+            echo '${{ secrets.APPSETTINGS_JSON_CART }}' > src/Services/Cart/Cart.API/appsettings.json
+              try {
+                ConvertFrom-Json -InputObject '${{ secrets.APPSETTINGS_JSON_CART }}' | Out-Null
+                Write-Host "JSON is valid."
+              } catch {
+                Write-Error "Invalid JSON format in appsettings.json"
+                exit 1
+              }
+        shell: pwsh    
+  
       - name: Build with dotnet
         run: dotnet build --configuration Release
-
+        working-directory: EduTrailblaze/
+  
       - name: dotnet publish
-        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
+        run: dotnet publish src/Services/Cart/Cart.API/Cart.API.csproj -c Release -o output
+  
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: .net-app
-          path: ${{env.DOTNET_ROOT}}/myapp
+          path: output
 
   deploy:
     runs-on: windows-latest
