Update main_edu-trailblaze.yml

diff --git a/.github/workflows/main_edu-trailblaze.yml b/.github/workflows/main_edu-trailblaze.yml
--- a/.github/workflows/main_edu-trailblaze.yml
+++ b/.github/workflows/main_edu-trailblaze.yml
@@ -12,8 +12,6 @@ on:
 jobs:
   build:
     runs-on: windows-latest
-    permissions:
-      contents: read #This is required for actions/checkout
 
     steps:
       - uses: actions/checkout@v4
@@ -21,19 +19,52 @@ jobs:
       - name: Set up .NET Core
         uses: actions/setup-dotnet@v4
         with:
-          dotnet-version: '8.x'
+          dotnet-version: '8.0.x'
+      
+      - name: Set ASPNETCORE_ENVIRONMENT
+        run: echo "ASPNETCORE_ENVIRONMENT=Production" >> $GITHUB_ENV
+
+      - name: Add appsettings.json
+        run: |
+          echo '${{ secrets.APPSETTINGS_JSON }}' > EduTrailblaze/EduTrailblaze.API/appsettings.json
+          try {
+            ConvertFrom-Json -InputObject '${{ secrets.APPSETTINGS_JSON }}' | Out-Null
+            Write-Host "JSON is valid."
+          } catch {
+            Write-Error "Invalid JSON format in appsettings.json"
+            exit 1
+          }
+        shell: pwsh
 
       - name: Build with dotnet
         run: dotnet build --configuration Release
+        working-directory: EduTrailblaze/
 
-      - name: dotnet publish
-        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
+      # - name: dotnet publish
+      #   run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
 
-      - name: Upload artifact for deployment job
+      - name: Publish API project
+        run: dotnet publish EduTrailblaze/EduTrailblaze.API/EduTrailblaze.API.csproj -c Release -o output
+      
+      - name: Debug Environment
+        run: printenv
+
+      # - name: Check .NET version
+      #   run: |
+      #     dotnet --info
+      #     dotnet workload list
+
+      - name: Upload artifact for deployment
         uses: actions/upload-artifact@v4
         with:
-          name: .net-app
-          path: ${{env.DOTNET_ROOT}}/myapp
+            name: .net-app
+            path: output
+      
+      - name: Clean deployment directory
+        run: |
+            echo "Cleaning output directory..."
+            rm -rf ./output/*
+        shell: bash
 
   deploy:
     runs-on: windows-latest
@@ -43,8 +74,7 @@ jobs:
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
       id-token: write #This is required for requesting the JWT
-      contents: read #This is required for actions/checkout
-
+    
     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
@@ -57,6 +87,14 @@ jobs:
           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8C3517BD2B7D49F5842D283DF9F61615 }}
           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_81CDB63281EC42F985D9B32D87A775D1 }}
           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F5CE5E217B534D01AFE00C975D532C16 }}
+
+      - name: Clean Azure Web App Deployment
+        run: |
+            echo "Cleaning up old deployment files..."
+            az webapp deployment source config-zip --resource-group 'Edu-Trailblaze' --name 'edu-trailblaze' --src ./output.zip
+            echo "Cleaning cache..."
+            az webapp restart --name 'edu-trailblaze' --resource-group 'Edu-Trailblaze'
+        shell: pwsh
 
       - name: Deploy to Azure Web App
         id: deploy-to-webapp
