Update main_edu-gateway.yml

diff --git a/.github/workflows/main_edu-gateway.yml b/.github/workflows/main_edu-gateway.yml
--- a/.github/workflows/main_edu-gateway.yml
+++ b/.github/workflows/main_edu-gateway.yml
@@ -22,14 +22,26 @@ jobs:
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: '8.x'
-
+      
+      - name: Add appsettings.json
+        run: |
+            echo '${{ secrets.APPSETTINGS_JSON_GATEWAY }}' > EduTrailblaze/OcelotApiGw/appsettings.json
+              try {
+                ConvertFrom-Json -InputObject '${{ secrets.APPSETTINGS_JSON_CART }}' | Out-Null
+                Write-Host "JSON is valid."
+              } catch {
+                Write-Error "Invalid JSON format in appsettings.json"
+                exit 1
+              }
+        shell: pwsh   
+        
       - name: Build with dotnet
         run: dotnet build --configuration Release
         working-directory: EduTrailblaze/
 
       - name: dotnet publish
         run: dotnet publish EduTrailblaze/OcelotApiGw/OcelotApiGw.csproj -c Release -o output
-
+        
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
